name: pytorch_pih
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - pip:
      - numpy
      - pandas
      - jupyter
      - tqdm
      - pillow
      - matplotlib
      - opencv-python
